version: "3.9"

networks:
  jenkins:
    external: false
    
services:
  jenkins:
    build: .
    image: jenkins_image
    container_name: jenkins_container
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8080:8080